### PR TITLE
V2 accordions change in behavior

### PR DESCRIPTION
**Pull request by msecret**
This makes it so when an already opened item is clicked it will close
that item, not do nothing. The result of the attr if json parsed so
that its becomes an actual boolean.

The width on the ul was changed because before the content div was
setting the width, so when none are displaying it breaks the layout.

### CODE REVIEW

**Comment by maya** [comment]
@msecret the behavior is working but are you working off of the latest accordions? There should be 2 versions: borderless and bordered. Another thing that's missing is the new hover styles.

**Comment by maya** [comment]
Also there should be a `<div class="preview">...</div>` wrapped around all examples which appears to be missing here. The reason why is bc I'm going to need to grab this class with JS to output our markup for the code examples.

**Comment by msecret** [comment]
I moved this here as there was a problem with the tracking on this branch: https://github.com/18F/usfwds/pull/351

**Comment by maya** [comment]
Closing in favor of: https://github.com/18F/usfwds/pull/351

**Pull request closed without merging**
